name: PluginHub
version: 1.1
description: "Advanced plugin manager for Paper servers - Search, install, update plugins with favorites, profiles, backups and history tracking"
author: Pecar
main: com.pluginhub.PluginHub
api-version: 1.21

commands:
  pluginhub:
    description: "Main command for PluginHub"
    usage: "/pluginhub <search|install|update|list> <plugin-name>"
    aliases: [ph, plugins]
  phsearch:
    description: "Search for plugins across all repositories"
    usage: "/phsearch <plugin-name>"
  phinstall:
    description: "Install a plugin automatically"
    usage: "/phinstall <plugin-name>"
  phupdate:
    description: "Update all or specific plugins"
    usage: "/phupdate [plugin-name]"
  phfavorite:
    description: "Manage favorite plugins"
    usage: "/phfavorite <add|remove|list|clear> [plugin-name]"
    aliases: [phfav]
  phhistory:
    description: "View installation history"
    usage: "/phhistory [plugin-name]"
    aliases: [phhist]
  phprofile:
    description: "Manage plugin profiles"
    usage: "/phprofile <list|info|create|delete|install|add|remove> [args]"
    aliases: [phprof]
  phbackup:
    description: "Manage plugin backups"
    usage: "/phbackup <create|restore|list|delete> <plugin-name> [backup-name]"
    aliases: [phbak]
  phinfo:
    description: "View detailed plugin information"
    usage: "/phinfo <plugin-name>"

permissions:
  pluginhub.admin:
    description: "Access to all PluginHub commands"
    default: op
    children:
      pluginhub.search: true
      pluginhub.install: true
      pluginhub.update: true
      pluginhub.favorite: true
      pluginhub.history: true
      pluginhub.profile: true
      pluginhub.backup: true
      pluginhub.info: true
  pluginhub.search:
    description: "Permission to search for plugins"
    default: true
  pluginhub.install:
    description: "Permission to install plugins"
    default: op
  pluginhub.update:
    description: "Permission to update plugins"
    default: op
  pluginhub.favorite:
    description: "Permission to manage favorites"
    default: op
  pluginhub.history:
    description: "Permission to view history"
    default: op
  pluginhub.profile:
    description: "Permission to manage profiles"
    default: op
  pluginhub.backup:
    description: "Permission to manage backups"
    default: op
  pluginhub.info:
    description: "Permission to view plugin info"
    default: true
